"use client";

import { useState } from "react";
import ToolPageLayout from "@/components/ToolPageLayout";
import { FileCode, Copy, RefreshCcw, Check, Plus, Trash2 } from "lucide-react";

export default function RobotsGenerator() {
  const [copied, setCopied] = useState(false);
  const [rules, setRules] = useState([
    { userAgent: "*", disallow: "/admin/" },
    { userAgent: "Googlebot", disallow: "/tmp/" }
  ]);
  const [sitemap, setSitemap] = useState("https://yourwebsite.com/sitemap.xml");

  const addRule = () => setRules([...rules, { userAgent: "", disallow: "" }]);
  const removeRule = (idx: number) => setRules(rules.filter((_, i) => i !== idx));
  const updateRule = (idx: number, field: string, val: string) => {
    const newRules = [...rules];
    (newRules[idx] as any)[field] = val;
    setRules(newRules);
  };

  const generateCode = () => {
    let code = "# robots.txt generated by TOOLS TEKNO\n\n";
    rules.forEach(rule => {
      if (rule.userAgent) code += `User-agent: ${rule.userAgent}\n`;
      if (rule.disallow) code += `Disallow: ${rule.disallow}\n`;
      code += "\n";
    });
    if (sitemap) code += `Sitemap: ${sitemap}\n`;
    return code.trim();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <ToolPageLayout
      title="Robots.txt Generator"
      description="Create a custom robots.txt file to guide search engines on how to crawl your site."
      icon={FileCode}
      slug="robots-generator"
    >
      <div className="space-y-8">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-bold text-slate-900 dark:text-white">Crawl Rules</h3>
            <button
              onClick={addRule}
              className="px-3 py-1.5 bg-primary/10 text-primary text-xs font-bold rounded-lg flex items-center gap-1.5 hover:bg-primary/20 transition-colors"
            >
              <Plus className="w-3.5 h-3.5" />
              Add Rule
            </button>
          </div>

          <div className="space-y-3">
            {rules.map((rule, idx) => (
              <div key={idx} className="flex gap-4 items-end animate-in fade-in slide-in-from-left-2 duration-300">
                <div className="flex-1 space-y-2">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">User-agent</label>
                  <input
                    type="text"
                    value={rule.userAgent}
                    onChange={(e) => updateRule(idx, "userAgent", e.target.value)}
                    placeholder="*"
                    className="w-full px-4 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 outline-none text-sm"
                  />
                </div>
                <div className="flex-1 space-y-2">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Disallow Path</label>
                  <input
                    type="text"
                    value={rule.disallow}
                    onChange={(e) => updateRule(idx, "disallow", e.target.value)}
                    placeholder="/admin/"
                    className="w-full px-4 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 outline-none text-sm"
                  />
                </div>
                <button
                  onClick={() => removeRule(idx)}
                  className="p-2.5 text-slate-400 hover:text-red-500 transition-colors"
                >
                  <Trash2 className="w-5 h-5" />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="space-y-2">
          <label className="block text-xs font-bold text-slate-900 dark:text-white">Sitemap URL (Optional)</label>
          <input
            type="text"
            value={sitemap}
            onChange={(e) => setSitemap(e.target.value)}
            className="w-full px-4 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 outline-none text-sm"
          />
        </div>

        <div className="pt-6 border-t border-slate-100 dark:border-slate-800">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm font-bold text-slate-700 dark:text-slate-300">Preview</span>
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 text-xs font-bold text-primary px-3 py-1.5 rounded-lg bg-primary/5 hover:bg-primary/10 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied!" : "Copy Output"}
            </button>
          </div>
          <pre className="w-full p-4 rounded-xl bg-slate-900 text-blue-300 font-mono text-xs leading-relaxed overflow-auto min-h-[150px]">
            {generateCode()}
          </pre>
        </div>
      </div>
    </ToolPageLayout>
  );
}
