"use client";

import { useState, useEffect } from "react";
import ToolPageLayout from "@/components/ToolPageLayout";
import { 
  FileCode, 
  Copy, 
  Check, 
  ShieldAlert, 
  Lock, 
  Zap, 
  Globe, 
  ShieldCheck,
  RefreshCcw,
  Terminal
} from "lucide-react";

export default function HtaccessGenerator() {
  const [copied, setCopied] = useState(false);
  const [options, setOptions] = useState({
    forceHttps: true,
    forceWww: false,
    preventListing: true,
    custom404: "/404.html",
    // New Advanced Features
    enableGzip: true,
    browserCaching: true,
    hsts: true,
    nosniff: true,
    xssProtection: true,
    frameOptions: "SAMEORIGIN",
    ipBlocking: "",
  });

  const [generatedCode, setGeneratedCode] = useState("");

  const generateCode = () => {
    let code = "# .htaccess generated by TOOLS TEKNO PRO\n\n";
    
    code += "RewriteEngine On\n\n";

    if (options.forceHttps) {
      code += "# Force HTTPS\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n";
    }
    
    if (options.forceWww) {
      code += "# Force WWW\nRewriteCond %{HTTP_HOST} !^www\\. [NC]\nRewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n";
    }
    
    if (options.preventListing) {
      code += "# Disable Directory Listing\nOptions -Indexes\n\n";
    }

    if (options.enableGzip) {
      code += "# Enable Gzip Compression\n<IfModule mod_deflate.c>\n    AddOutputFilterByType DEFLATE text/plain text/html text/xml text/css application/xml application/xhtml+xml application/rss+xml application/javascript application/x-javascript\n</IfModule>\n\n";
    }

    if (options.browserCaching) {
      code += "# Browser Caching (Expires Headers)\n<IfModule mod_expires.c>\n    ExpiresActive On\n    ExpiresByType image/jpg \"access 1 year\"\n    ExpiresByType image/jpeg \"access 1 year\"\n    ExpiresByType image/gif \"access 1 year\"\n    ExpiresByType image/png \"access 1 year\"\n    ExpiresByType text/css \"access 1 month\"\n    ExpiresByType application/pdf \"access 1 month\"\n    ExpiresByType text/x-javascript \"access 1 month\"\n    ExpiresDefault \"access 2 days\"\n</IfModule>\n\n";
    }
    
    code += "# Security Headers\n";
    if (options.hsts) code += "Header set Strict-Transport-Security \"max-age=31536000; includeSubDomains; preload\" env=HTTPS\n";
    if (options.nosniff) code += "Header set X-Content-Type-Options \"nosniff\"\n";
    if (options.xssProtection) code += "Header set X-XSS-Protection \"1; mode=block\"\n";
    if (options.frameOptions) code += `Header set X-Frame-Options \"${options.frameOptions}\"\n`;
    code += "\n";

    if (options.custom404) {
      code += `# Custom Error Pages\nErrorDocument 404 ${options.custom404}\n\n`;
    }

    if (options.ipBlocking) {
      const ips = options.ipBlocking.split(",").map(ip => ip.trim()).filter(ip => ip);
      if (ips.length > 0) {
        code += "# IP Blocking\n<Limit GET POST>\n    order allow,deny\n    allow from all\n";
        ips.forEach(ip => {
          code += `    deny from ${ip}\n`;
        });
        code += "</Limit>\n\n";
      }
    }

    return code.trim();
  };

  useEffect(() => {
    setGeneratedCode(generateCode());
  }, [options]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <ToolPageLayout
      title="htaccess Master PRO"
      description="Professional-grade Apache configuration generator with security hardening and performance optimization."
      icon={FileCode}
      slug="htaccess"
    >
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        <div className="space-y-8">
          <div className="bg-primary/5 p-4 rounded-2xl border border-primary/10 flex items-center gap-3">
            <ShieldAlert className="w-5 h-5 text-primary shrink-0" />
            <span className="text-sm font-bold text-primary">Advanced PRO Logic Enabled</span>
          </div>

          {/* Basic Redirects */}
          <div className="space-y-4">
            <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
              <Globe className="w-4 h-4" />
              Routing & Redirects
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                { label: "Force HTTPS", key: "forceHttps" },
                { label: "Force WWW", key: "forceWww" },
                { label: "Disable Directory Listing", key: "preventListing" },
                { label: "Gzip Compression", key: "enableGzip" },
              ].map((item) => (
                <button
                  key={item.key}
                  onClick={() => setOptions({ ...options, [item.key]: !(options as any)[item.key] })}
                  className={`flex items-center justify-between p-4 rounded-xl border text-left transition-all ${
                    (options as any)[item.key] 
                      ? "bg-primary/10 border-primary text-primary" 
                      : "bg-card border-border text-muted-foreground hover:border-slate-300"
                  }`}
                >
                  <span className="text-xs font-bold leading-tight">{item.label}</span>
                  {(options as any)[item.key] ? <Check className="w-4 h-4 shrink-0" /> : <RefreshCcw className="w-3 h-3 shrink-0 opacity-50" />}
                </button>
              ))}
            </div>
          </div>

          {/* Security Suite */}
          <div className="space-y-4">
            <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
              <Lock className="w-4 h-4" />
              Security Hardening
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                { label: "HSTS Header", key: "hsts" },
                { label: "X-Content (nosniff)", key: "nosniff" },
                { label: "XSS Protection", key: "xssProtection" },
                { label: "Browser Caching", key: "browserCaching" },
              ].map((item) => (
                <button
                  key={item.key}
                  onClick={() => setOptions({ ...options, [item.key]: !(options as any)[item.key] })}
                  className={`flex items-center justify-between p-4 rounded-xl border text-left transition-all ${
                    (options as any)[item.key] 
                      ? "bg-green-500/10 border-green-500 text-green-600 dark:text-green-400" 
                      : "bg-card border-border text-muted-foreground hover:border-slate-300"
                  }`}
                >
                  <span className="text-xs font-bold leading-tight">{item.label}</span>
                  {(options as any)[item.key] ? <ShieldCheck className="w-4 h-4 shrink-0" /> : <RefreshCcw className="w-3 h-3 shrink-0 opacity-50" />}
                </button>
              ))}
            </div>
          </div>

          {/* Advanced Inputs */}
          <div className="space-y-4 pt-4">
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-400 uppercase tracking-widest">IP denylist (comma separated)</label>
              <input
                type="text"
                value={options.ipBlocking}
                onChange={(e) => setOptions({ ...options, ipBlocking: e.target.value })}
                placeholder="1.2.3.4, 5.6.7.8"
                className="w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 outline-none text-sm font-semibold"
              />
            </div>
          </div>
        </div>

        {/* Output Section */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
              <Terminal className="w-4 h-4" />
              Directives Output
            </h3>
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 text-xs font-bold text-primary px-3 py-1.5 rounded-lg bg-primary/5 hover:bg-primary/10 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied!" : "Copy .htaccess"}
            </button>
          </div>
          <div className="relative group">
            <pre className="w-full p-6 rounded-2xl bg-slate-900 text-blue-300 font-mono text-[11px] leading-relaxed overflow-auto min-h-[500px] border border-slate-800">
              {generatedCode}
            </pre>
            <div className="absolute bottom-4 right-4 text-[10px] font-bold text-slate-700 uppercase tracking-widest select-none">
              Apache/2.4 Config
            </div>
          </div>
          <div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/10 flex items-start gap-3">
             <Zap className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
             <p className="text-[10px] text-amber-700 dark:text-amber-400 font-medium leading-relaxed">
               Always backup your existing .htaccess file before applying new rules. Misconfiguration can cause 500 Internal Server Errors.
             </p>
          </div>
        </div>
      </div>
    </ToolPageLayout>
  );
}
